### ISSUE TITLE
YASGUI version deprecated

### ISSUE THREAD

**Issue by kayakr** [AucklandMuseum/API#1]
Under "Create queries using the SPARQL endpoint" at https://www.aucklandmuseum.com/discover/collections-online/our-data the "Try it out" button links to http://yasgui.org/#query=PREFIX+am%3A+%3Chttp%3A%2F%2Fcollections.aucklandmuseum.com%2Fontology%2Fcore%2F%3E%0APREFIX+xsd%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0APREFIX+ecrm%3A+%3Chttp%3A%2F%2Ferlangen-crm.org%2Fcurrent%2F%3E%0APREFIX+rdf%3A%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0A%0A%0ASELECT+%3Fdept+(count(%3Fdept)+as+%3Fcount)%7B%0A++%3Fa+ecrm%3AP50_has_current_keeper%2Frdf%3Avalue+%3Fdept.%0A++%7D%0Agroup+by++%3Fdept&contentTypeConstruct=text%2Fturtle&contentTypeSelect=application%2Fsparql-results%2Bjson&endpoint=http%3A%2F%2Fapi.aucklandmuseum.com%2Fsparql%3F&requestMethod=POST&tabTitle=Query+20&headers=%7B%7D&outputFormat=table

That UI has a banner "This YASGUI version is deprecated. As of the 15th of February, we will redirect to https://yasgui.triply.cc.
To avoid losing your locally stored queries, copy these queries to the new version."

**Comment by kayakr** [comment]
FYI, the https://yasgui.triply.cc YASGUI instance appears to work, but only if the POST Header argument is set to Accept: application/sparql-results+json using the gear icon:

https://yasgui.triply.cc/#query=PREFIX%20am%3A%20%3Chttp%3A%2F%2Fcollections.aucklandmuseum.com%2Fontology%2Fcore%2F%3E%0APREFIX%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0APREFIX%20ecrm%3A%20%3Chttp%3A%2F%2Ferlangen-crm.org%2Fcurrent%2F%3E%0APREFIX%20rdf%3A%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0A%0A%0ASELECT%20(count(%3Fdept)%20as%20%3Fcount)%20%3Fdept%20%7B%0A%20%20%3Fa%20ecrm%3AP50_has_current_keeper%2Frdf%3Avalue%20%3Fdept.%0A%20%20%7D%0Agroup%20by%20%20%3Fdept&endpoint=https%3A%2F%2Fapi.aucklandmuseum.com%2Fsparql%3F&requestMethod=GET&tabTitle=Query&headers=%7B%22Accept%22%3A%22application%2Fsparql-results%2Bjson%22%7D&contentTypeConstruct=text%2Fturtle%2C*%2F*%3Bq%3D0.9&contentTypeSelect=application%2Fsparql-results%2Bjson%2C*%2F*%3Bq%3D0.9&outputFormat=table

**Comment by hughlilly** [comment]
Thanks @kayakr; I've updated the link on that page to point to:
`http://yasgui.triply.cc/#query=PREFIX%20am%3A%20%3Chttp%3A%2F%2Fcollections.aucklandmuseum.com%2Fontology%2Fcore%2F%3E%0APREFIX%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0APREFIX%20ecrm%3A%20%3Chttp%3A%2F%2Ferlangen-crm.org%2Fcurrent%2F%3E%0APREFIX%20rdf%3A%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0A%0A%0ASELECT%20%3Fdept%20(count(%3Fdept)%20as%20%3Fcount)%7B%0A%20%20%3Fa%20ecrm%3AP50_has_current_keeper%2Frdf%3Avalue%20%3Fdept.%0A%20%20%7D%0Agroup%20by%20%20%3Fdept&endpoint=http%3A%2F%2Fapi.aucklandmuseum.com%2Fsparql%3F&requestMethod=POST&tabTitle=AM_Departments&headers=%7B%22Accept%22%3A%22application%2Fsparql-results%2Bjson%22%7D`

This includes the Accept: header as a URL parameter.
