### ISSUE TITLE
Ephemera link in tutorial returns 404

### ISSUE THREAD

**Issue by kayakr** [AucklandMuseum/API#3]
At https://github.com/AucklandMuseum/API/wiki/Tutorial#how-to-find-a-record-if-you-know-the-id the link to http://api.aucklandmuseum.com/id/library/ephemera/13270 redirects to https://api.aucklandmuseum.com/id/library/ephemera/13270 that returns 404

**Comment by hughlilly** [comment]
That record has been taken offline since that tutorial was written; I've replaced it with another example record.
