### ISSUE TITLE
How to fetch all data for a person record

### ISSUE THREAD

**Issue by kayakr** [AucklandMuseum/API#4]
I want to fetch structured data for person, e.g.
`curl  -H 'Accept: application/json' https://api.aucklandmuseum.com/id/person/C924`

This works, but only gives the top level of values, similar to HTML view.
e.g. https://api.aucklandmuseum.com/id/person/C924

I would need to iterate over tens of URLs to fetch literal values for the entire object:
e.g https://api.aucklandmuseum.com/id/person/C924
shows http://collections.aucklandmuseum.com/ontology/core/cemetery
maps to object http://api.aucklandmuseum.com/id/person/C924/cemetery/0
which in turn http://api.aucklandmuseum.com/id/person/C924/cemetery/0
http://collections.aucklandmuseum.com/ontology/core/restingPlace, object=Caterpillar Valley Cemetery, Longueval, Somme, France

Is there a way to return the full depth of the object on one request, graphql-style?

**Comment by hughlilly** [comment]
Hi @kayakr, I've been told there isn't a way to do this, unfortunately. You just need to make a series of calls.

We also have [a SPARQL endpoint](https://api.aucklandmuseum.com/sparql) if that would suit your needs; I've got some queries here that might be of use:
https://gist.github.com/hughlilly/f177b9c97d0aaff129770f773caf5258

Cheers
Hugh
